#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

$POSTGRES <<-EOSQL

--create empty roles
CREATE ROLE read_only with NOLOGIN;
CREATE ROLE read_write with NOLOGIN;

--Create our User with passwords set in the environment spinup
CREATE ROLE sa WITH LOGIN ENCRYPTED PASSWORD '${SA_PASS}' SUPERUSER CREATEDB CREATEROLE INHERIT;
CREATE ROLE nfl_api WITH LOGIN ENCRYPTED PASSWORD '${API_PASS}' IN ROLE read_write INHERIT;

--ACCESS DB
REVOKE CONNECT ON DATABASE ${POSTGRES_DB} FROM PUBLIC;
GRANT  CONNECT ON DATABASE ${POSTGRES_DB} TO nfl_api, sa;

--ACCESS SCHEMA
REVOKE ALL     ON SCHEMA public FROM PUBLIC;
GRANT  USAGE   ON SCHEMA public  TO nfl_api,read_only,read_write ;

REVOKE ALL ON SEQUENCES FROM PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO read_write, read_only;

--ACCESS TABLES
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC ;

EOSQL
